default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: 123321
  database: gift

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
  database: <%= "#{ENV['DB_NAME']}-test" %>
